### ISSUE TITLE
DVB-DASH interop point identifiers

### ISSUE THREAD

**Issue by wschidol** [c-alpha/metadata-website#6]
DVB document ETSI TS 103285 defines identifiers urn:dvb:dash:profile:dvb-dash:2014 and urn:dvb:dash:profile:dvb-dash:2017. Should these be listed in here?

**Comment by c-alpha** [comment]
Apologies for the delay.

The metadata page lists namespaces of instance documents, but not the code points defined within these instance documents.

If there's a new revision of TS 103 285 (which I seem to infer from your question), that new version should be added to the page.

**Comment by c-alpha** [comment]
Moved to Bugzilla (cc-ed @wschidol there).
